### ISSUE TITLE
Could not load package

### ISSUE THREAD

**Issue by Xiaoxi-Hu** [fernandoPalluzzi/SEMgraph#13]
Dear Fernando,

Nice to see you! I truly appreciate your contribution to this amazing R package. However, I meet a small problem and am trying to seek your help. When I tried to load your package by _library()_, an error occurred, saying that "_Error: package or namespace load failed for ‘SEMgraph’: object ‘ggm_compare’ is not exported by 'namespace:GGMncv'_". I found that the version of GGMncv needs to be ≥ 2.0.0, of which mine is 2.1.1. And I could not find _GGMncv::ggm_compare()_ function. So I am kind of confused about why this happens and looking forwards to your kind help! 

Thanks so much!

Best,
Corinna

**Comment by fernandoPalluzzi** [comment]
Dear Corinna,

Thank you for your interest in SEMgraph!
Recently, GGMncv has been upgraded to a new version, and some of the functions and related outputs has been changed a bit. This caused a temporary break in SEMgraph code.
I've just fixed the issue and I'm going to upload the new CRAN version of SEMgraph (1.0.5) in a few hours, after some last minor checks.

Thank you again for using SEMgraph!

Best,
Fernando

**Comment by Xiaoxi-Hu** [comment]
Dear Fernando,

Thank you so much for your quick and kind reply, which is truly helpful! I am the one who should say thank you for your contribution to such an outstanding tool for us. I am looking forwards to applying SEMgraph!

Best,
Corinna

**Comment by fernandoPalluzzi** [comment]
Dear Corinna,

I'm writing just to inform you that the CRAN package will be soon available. We delayed for maintainer change: my current position does not allow me to give constant support to the CRAN version.
You may download my SEMgraph 1.0.5 development version, on my GitHub page. This version is identical to the incoming CRAN one.

Best regards,

Fernando
