### ISSUE TITLE
Issue after updating to version 1.1.3

### ISSUE THREAD

**Issue by aldosc** [fernandoPalluzzi/SEMgraph#24]
Hi Fernando,

I've continued testing SEMgraph. However, something happened after updating to last version in CRAN. In the previous version, I was able to run SEMrun() function and completed the analysis with my own network and expression data. After the updated, this is not the case anymore. The error is not observed when using the datasets in the SEMdata package.
See the attached snapshot. 

Thanks!
<img width="486" alt="semrun" src="https://user-images.githubusercontent.com/40887687/204794274-6608ccea-2ee6-4f11-b396-4bd840fbbcf0.PNG">

**Comment by fernandoPalluzzi** [comment]
Hi Aldo,

Sorry for the delay in answering you. I've recently relocated from Italy to Denmark and had almost no time to work on SEMgraph.
I am now preparing version 1.1.4 of SEMgraph, dealing with the Brown test function error (the origin of your problem) and improving some other aspects.
For the time being, I hope you could work with version 1.1.2 (this won't affect the estimations). I'll get back to you as soon as version 1.1.4 is ready to  be shared.

Thanks for using SEMgraph!

Fernando

**Comment by fernandoPalluzzi** [comment]
Dear Aldo,

I've now updated the development version and the bugs you reported should be solved. This is not the stable (CRAN) version yet, but you can use it and tell me how it goes.
I'll be waiting for you to double check it before closing this issue.

Thanks,

Fernando

**Comment by aldosc** [comment]
Happy new year Fernando,

The issue with the Brown test function is now fixed, Thanks!

**Comment by fernandoPalluzzi** [comment]
Hi Aldo,
Happy new year to you too!

Great. Thank you for spotting the issue and help fixing it!
