### ISSUE TITLE
Possible to avoid hard dependence on dagitty?

### ISSUE THREAD

**Issue by barracuda156** [fernandoPalluzzi/SEMgraph#35]
`dagitty` requires V8, which is broken for some platforms. Is it possible to make it a soft dependence?

**Comment by fernandoPalluzzi** [comment]
Hi there. Sorry for such a late answer. SEMgraph development version was discontinued for a while when I relocated, but I'm now restarting it.

Unfortunately, dagitty is a critical dependency for dag estimation in SEMdag functions, and I am not aware of a pachage that can efficiently substitute it, also in terms of code optimization. If you are aware of any alternative solutions, I will definitely take them into account for my new implementation.

I will close the thread but feel free to reopen it for any suggestion.
